// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/chat/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/profile" | "/users" | "/chat" | "/chat/:userId";
  };
  "../pages/Home.tsx": {
    id: "../pages/Home";
    page: "/";
  };
  "../pages/Login.tsx": {
    id: "../pages/Login";
    page: "/login";
  };
  "../pages/Signup.tsx": {
    id: "../pages/Signup";
    page: "/signup";
  };
  "../pages/Profile.tsx": {
    id: "../pages/Profile";
    page: "/profile";
  };
  "../pages/Users.tsx": {
    id: "../pages/Users";
    page: "/users";
  };
  "../pages/Chat.tsx": {
    id: "../pages/Chat";
    page: "/chat" | "/chat/:userId";
  };
  "../features/Chat/Main.tsx": {
    id: "../features/Chat/Main";
    page: "/chat";
  };
  "../features/Chat/ChatRoom.tsx": {
    id: "../features/Chat/ChatRoom";
    page: "/chat/:userId";
  };
};

type RouteModules = {
  "root": typeof import("./app/config/root.tsx");
  "../pages/Home": unknown;
  "../pages/Login": unknown;
  "../pages/Signup": unknown;
  "../pages/Profile": unknown;
  "../pages/Users": unknown;
  "../pages/Chat": unknown;
  "../features/Chat/Main": unknown;
  "../features/Chat/ChatRoom": unknown;
};