// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/chat/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/chat" | "/chat/:userId";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "./pages/Signup.tsx": {
    id: "pages/Signup";
    page: "/signup";
  };
  "./pages/Chat.tsx": {
    id: "pages/Chat";
    page: "/chat" | "/chat/:userId";
  };
  "./components/Chat/Main.tsx": {
    id: "components/Chat/Main";
    page: "/chat";
  };
  "./components/Chat/ChatRoom.tsx": {
    id: "components/Chat/ChatRoom";
    page: "/chat/:userId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Home": typeof import("./app/./pages/Home.tsx");
  "pages/Login": typeof import("./app/./pages/Login.tsx");
  "pages/Signup": typeof import("./app/./pages/Signup.tsx");
  "pages/Chat": typeof import("./app/./pages/Chat.tsx");
  "components/Chat/Main": typeof import("./app/./components/Chat/Main.tsx");
  "components/Chat/ChatRoom": typeof import("./app/./components/Chat/ChatRoom.tsx");
};